{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mattermost.serviceAccountName" . }}
  labels:
{{ include "mattermost.labels" . | nindent 4 }}
{{- end -}}
